### ISSUE TITLE
Stuck Loading Index message 

### ISSUE THREAD

**Issue by CRTX** [m2mdas/phpcomplete-extended-symfony#3]
Sorry, probably should have seeked help here instead of Youtube.

Running VIM 7.4 with vanilla phpcomplete-extended and phpcomplete-extended-symfony.

Loading index message is suck so I don't really know when the plugin is usable.

By the way, this is also on a vanilla install of Symfony2 which has a handful of custom files.

Is the "Loading Index" message at the bottom of VIM supposed to disappear after a while?

**Comment by m2mdas** [comment]
Yes "Loading Index" message should disappear after the index is read. Can you issue `:PHPCompleteExtendedGenerateIndex` and `:PHPCompleteExtendedReload` command to see that any error message occurs? If so please post the error message.

**Comment by CRTX** [comment]
No error messages it's just when I run `:PHPCompleteExtendedReload` the `Loading Index` message doesn't disappear at all.

After I load a file with `:e file.txt` the message does disappear though.

**Comment by m2mdas** [comment]
Does Vim stuck when `Loading Index` message is shown?

**Comment by CRTX** [comment]
No, like I said I can load files at any time when that message appears.

**Comment by m2mdas** [comment]
Hmm, autocomplete also works I assume?

**Comment by CRTX** [comment]
Autocomplete works. But it didn't before. I think the only reason it started working is because I waited a few minutes to see if the message would disappear (even though it never did). Before I was just loading files after a few seconds since I didn't know how long it was going to take to load the index.

**Comment by m2mdas** [comment]
Yes you are right. Only showing `Loading Index` message can make confusion some time. I have updated `phpcomplete-extended` repo so that `Index Loaded.` will be shown after index is read. Please update `phpcomplete-extended`. Thanks for reporting this issue. 

Happy Coding!

**Comment by CRTX** [comment]
Gosh, I'm so happy right now with this plugin! Now if you only had a DogeCoin address so I could tip you. :P
